version: '3'
services:
  my-go-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../pkg:/var/task
    ports:
      - 9000:8080
    environment:
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_SESSION_TOKEN=
    command: ["main"]